export const weaponAbilities = {
  sword: [
    {
      name: "Evasion",
      hitChance: 80,
      stength: 1,
      luck: -2,
      range: 1,
      uses: 1,
      type: "Efficiency",
      effect: "1.3x Eva against certain units",
    },
    {
      name: "Sword Dance",
      hitChance: 75,
      stength: 2,
      skill: 2,
      range: 1,
      uses: 1,
      type: "Damage",
      effect: "Lowers accuracy to raise chance of evasion",
    },
    {
      name: "Tipper",
      hitChance: 80,
      stength: -1,
      skill: 5,
      range: 1,
      uses: 1,
      type: "Damage",
      effect: "Outranges the opponent",
    },
    {
      name: "Crescent Slash",
      hitChance: 80,
      stength: -1,
      range: 1,
      uses: 1,
      type: "Radial",
      effect: "Swings the sword in a circle hitting all adjacent foes.",
    },
    {
      name: "Foul Play",
      hitChance: 80,
      stength: 1,
      range: 1,
      uses: 1,
      type: "Obscuring",
      effect:
        "Kicks up a cloud of dirt, then attacks through the smoke. Enemy acc cut for counter attack",
    },
    {
      name: "Gouge",
      hitChance: 75,
      range: 1,
      uses: 1,
      type: "Blinding",
      effect: "Gouges the eyes, leaving the opponent blind for one turn.",
    },
    {
      name: "Shadow Blade",
      hitChance: 75,
      stength: -1,
      range: 1,
      uses: 1,
      type: "Maiming",
      effect:
        "Ultimate evasive attack, if landed unit disappears, preventing counter attack, and unit moves back 1 space",
    },
  ],
  axe: [
    {
      name: "Breaker",
      hitChance: 70,
      strength: 3,
      speed: -1,
      Luck: -2,
      range: 1,
      uses: 1,
      type: "Efficiency",
      effect: "1.3x Pwr against certain units",
    },
    {
      name: "Tomahawk",
      hitChance: 70,
      range: 2,
      uses: 1,
      type: "Damage",
      effect: "Hurls a tomahawk axe from 2 spaces away",
    },
    {
      name: "Armor Cleaver",
      hitChance: 70,
      range: 1,
      uses: 1,
      type: "Piercing",
      effect: "Cleaves through opponents armor, negating enemy protection",
    },
    {
      name: "Rend",
      hitChance: 70,
      strength: -1,
      range: 1,
      uses: 1,
      type: "Radial",
      effect:
        "Splits the earth in two, damaging three spaces in front vertically",
    },
    {
      name: "Dismember",
      hitChance: 75,
      strength: 1,
      range: 1,
      uses: 1,
      type: "Maiming",
      effect: "Slices through limbs, preventing a counter attack",
    },
    {
      name: "Bludgeon",
      hitChance: 70,
      range: 1,
      uses: 1,
      type: "Injuring",
      effect:
        "Hobbles the limb of the opponent leaving the injured status effect (1 turn)",
    },
    {
      name: "Ragnarok",
      hitChance: 65,
      strength: 6,
      defense: -1,
      speed: -1,
      range: 1,
      uses: 1,
      type: "Damage",
      effect: "Leaps into the air sacrificing control for a devastating blow",
    },
  ],
  dagger: [
    {
      name: "Acceleration",
      hitChance: 85,
      defense: -1,
      luck: -2,
      range: 1,
      uses: 1,
      type: "Efficiency",
      effect: "1.3x Aglty against certain units",
    },
    {
      name: "Throwing Knives",
      hitChance: 80,
      strength: -1,
      range: 2,
      uses: 1,
      type: "Damage",
      effect: "Throws a knife hitting an enemy from 2 spaces away",
    },
    {
      name: "Puncture",
      hitChance: 80,
      range: 1,
      uses: 1,
      type: "Piercing",
      effect:
        "Slips the dagger between armor plates, negating enemy protection",
    },
    {
      name: "Flurry",
      hitChance: 75,
      strength: -1,
      range: 1,
      uses: 1,
      type: "Radial",
      effect:
        "Spins violently throwing knives in each direction, damaging enemies 2 spaces away (x pattern)",
    },
    {
      name: "Pin",
      hitChance: 85,
      range: 1,
      uses: 1,
      type: "Immobalizing",
      effect:
        "Pins enemy feet to the floor with a small dagger, rendering them immobilized for one turn",
    },
    {
      name: "Stagnate",
      hitChance: 85,
      range: 1,
      uses: 1,
      type: "Slowing",
      effect:
        "Stabs the enemy with a toxin, slowing their movement for a turn.",
    },
    {
      name: "Blitz",
      hitChance: 75,
      defense: -1,
      range: 1,
      uses: 1,
      type: "Brave",
      effect: "Attatcks the enemy twice before the other can attack.",
    },
  ],
  lance: [
    {
      name: "Guard",
      hitChance: 75,
      strength: 1,
      luck: -2,
      range: 1,
      uses: 1,
      type: "Efficiency",
      effect: "1.3x Prt against certain units",
    },
    {
      name: "Javelin",
      hitChance: 75,
      range: 2,
      uses: 1,
      type: "Damage",
      effect:
        "Throws a javelin through the air hitting an opponent from two spaces away.",
    },
    {
      name: "Spear Sweep",
      hitChance: 70,
      strength: -1,
      range: 1,
      uses: 1,
      type: "Radial",
      effect:
        "Swings the tip of the spear in a wide arc hitting 3 enemies in front, pushing them back 1 space.",
    },
    {
      name: "Run Through",
      hitChance: 80,
      strength: 1,
      range: 1,
      uses: 1,
      type: "Damage",
      effect:
        "Impales and opponent moving them and the attacker back one space together.",
    },
    {
      name: "Shaft Check",
      hitChance: 80,
      strength: -2,
      defense: 6,
      range: 1,
      uses: 1,
      type: "Damage",
      effect:
        "Attacks with the shaft of the lance, increasing defensive readiness",
    },
    {
      name: "Spell Spear",
      hitChance: 80,
      strength: -2,
      resistance: 6,
      range: 1,
      uses: 1,
      type: "Damage",
      effect:
        "Douses the lance in special oil then attacks, warding off magick power.",
    },
    {
      name: "Gore",
      hitChance: 75,
      strength: 1,
      range: 1,
      uses: 1,
      type: "Damage",
      effect:
        "Uses lance to pull unit (2 spaces away) to adjacent space, then attacks. ",
    },
  ],
  bow: [
    {
      name: "Precision",
      hitChance: 85,
      strength: 1,
      luck: -2,
      range: 2,
      uses: 1,
      type: "Efficiency",
      effect: "1.3x Acc against certain units.",
    },
    {
      name: "Snipe",
      hitChance: 80,
      strength: 1,
      range: 3,
      uses: 1,
      type: "Damage",
      effect: "Snipes an enemy from 3 spaces away.",
    },
    {
      name: "Deadeye",
      hitChance: 100,
      strength: -1,
      range: 2,
      uses: 1,
      type: "Damage",
      effect: "Shoots an arrown with incredible accuracy.",
    },
    {
      name: "Explosive Volley",
      hitChance: 75,
      range: 3, //hits adjacent enemies. Original range per Brandons sheet is 2-4
      uses: 1,
      type: "Meteor",
      effect:
        "Launches an arrow rigged with explosives. Does 1/3 damage to adjacent enemies.",
    },
    {
      name: "Hit and Run",
      hitChance: 80,
      strength: -1,
      range: 2,
      uses: 1,
      type: "Damage",
      effect:
        "Attacks enemy unit and then moves back a space following the attack.",
    },
    {
      name: "Tome Breaker",
      hitChance: 80,
      strength: -1,
      resistance: -1,
      range: 2,
      uses: 1,
      type: "Silencing",
      effect: "Shoots the tome out of a mages hand, silencing them for a turn",
    },
    {
      name: "Poison Arrow",
      hitChance: 75,
      strength: 2,
      range: 2,
      uses: 1,
      type: "Poisoning",
      effect:
        "Coats the tip of the arrow with toxin before firing, leaving the enemy poisoned for 2 turns.",
    },
  ],
  gauntlets: [
    {
      name: "Exploitation",
      hitChance: 80,
      strength: 2,
      range: 1,
      uses: 1,
      type: "Efficiency",
      effect: "1.3x Lck against certain units.",
    },
    {
      name: "Dual Finger Jab",
      hitChance: 75,
      strength: 1,
      luck: 1,
      range: 1,
      uses: 1,
      type: "Obscuring",
      effect: "Pokes the enemy unit in the eyes, obscuring their vision",
    },
    {
      name: "Vault",
      hitChance: 75,
      luck: 2,
      range: 1,
      uses: 1,
      type: "Radial",
      effect:
        "Launches off two opponents to reach a third two spaces away, all three take damage (L-pattern)",
    },
    {
      name: "Disarm",
      hitChance: 75,
      defense: 4,
      luck: 1,
      range: 1,
      uses: 1,
      type: "Damage",
      effect: "Attacks the enemies weapon, disarming them.",
    },
    {
      name: "Tome Kick",
      hitChance: 75,
      resistance: 4,
      luck: 1,
      range: 1,
      uses: 1,
      type: "Damage",
      effect: "Kicks the tome out of a mages hands.",
    },
    {
      name: "Skull Swing",
      hitChance: 80,
      strength: 1,
      luck: 1,
      range: 1,
      uses: 1,
      type: "Damage",
      effect:
        "Uses acrobatics to attack the head of the opponent and then land behind them. ",
    },
    {
      name: "Crit Fist",
      hitChance: 60,
      luck: 10,
      range: 1,
      uses: 1,
      type: "Damage",
      effect: "An incredibly lucky strike, if it lands. ",
    },
  ],
  fire: [
    {
      name: "Incinerate",
      hitChance: 70,
      defense: -1,
      magick: 7,
      resistance: -1,
      speed: -1,
      range: 1,
      uses: 1,
      type: "Damage",
      effect: "Fire explodes toward the enemy, incinerating them",
    },
    {
      name: "Eruption",
      hitChance: 75,
      magick: 2,
      range: 1,
      uses: 1,
      type: "Radial",
      effect: "Flames erupt in all directions damaging 4 enemies (t pattern)",
    },
    {
      name: "Scorch",
      hitChance: 80,
      magick: 1,
      range: 2, //1-2
      uses: 1,
      type: "Burning",
      effect: "A less powerful blast of flame that leaves a burn for 2 turns",
    },
  ],
  water: [
    {
      name: "Dive",
      hitChance: 75,
      magick: -1,
      range: 1,
      uses: 1,
      type: "Obscuring",
      effect:
        "Dives into water after attacking, reducing accuracy for the counter attack",
    },
    {
      name: "Torrent",
      hitChance: 80,
      magick: -1,
      range: 1,
      uses: 1,
      type: "Radial",
      effect:
        "A torrent of water blasts 3 units, pushing them back if it hits (horizontal pattern)",
    },
    {
      name: "Ice Spear",
      hitChance: 80,
      magick: 1,
      range: 2, //1-2
      uses: 1,
      type: "Freezing",
      effect:
        "The mage summons an ice spear that pierces the flesh, leaving the enemy frozen for 2 turns",
    },
  ],
  earth: [
    {
      name: "Aegis",
      hitChance: 70,
      defense: 4,
      magick: -1,
      resistance: 4,
      range: 1,
      uses: 1,
      type: "Damage",
      effect:
        "The earths crust covers the body while attacking, leaving them nearly impregnable",
    },
    {
      name: "Quake",
      hitChance: 75,
      defense: 1,
      magick: -1,
      resistance: 1,
      range: 1,
      uses: 1,
      type: "Radial",
      effect:
        "A quake rends the earth, damaging three units in front (vertical pattern)",
    },
    {
      name: "Crush",
      hitChance: 75,
      magick: -1,
      range: 2, //1-2
      uses: 1,
      type: "Crushing",
      effect:
        "A boulder crushes the opponent's limb, causing damage for 2 turns",
    },
  ],
  lightning: [
    {
      name: "Static Speed",
      hitChance: 70,
      range: 1,
      uses: 1,
      type: "Brave",
      effect:
        "The body is infused with electricity, the ally attacks twice before the enemy can",
    },
    {
      name: "Discharge",
      hitChance: 80,
      magick: -1,
      range: 2,
      uses: 1,
      type: "Radial",
      effect:
        "Bolts of lighting explode outward, damaging 4 units 2 spaces away (x pattern)",
    },
    {
      name: "Thunder",
      hitChance: 80,
      speed: 1,
      range: 2, //1-2
      uses: 1,
      type: "Shocking",
      effect: "Thunder rains down on an enemy, shocking them for 2 turns",
    },
  ],
  grass: [
    {
      name: "Leech Life",
      hitChance: 80,
      range: 1,
      uses: 1,
      type: "Absorbtion",
      effect: "The enemy's life force is tapped into and absorbed",
    },
    {
      name: "Natures Grasp",
      hitChance: 80,
      magick: -1,
      range: 2, //1-2
      uses: 1,
      type: "Radial",
      effect:
        "Vines grab the legs of three units in front (horizontal pattern) and pull them in 1 space if hit",
    },
    {
      name: "Pin Needle",
      hitChance: 85,
      range: 2, //1-2
      uses: 1,
      type: "Poisoning",
      effect:
        "Countless poison needles are hurled toward the enemy, damaging them for 2 turns",
    },
  ],
  aether: [
    {
      name: "Clarity",
      hitChance: 100,
      magick: -2,
      range: 1,
      uses: 1,
      type: "Damage",
      effect: "All weather and obstacle dissipate, the enemy is seen perfectly",
    },
    {
      name: "Asteroid",
      hitChance: 80,
      range: 4, //2-4
      uses: 1,
      type: "Meteor",
      effect:
        "An asteroid crashes down from long range, doing 1/3 damage to adjacent enemies",
    },
    {
      name: "Gravity",
      hitChance: 85,
      range: 2, //1-2
      uses: 1,
      type: "Crushing",
      effect:
        "The crushing forces of gravity consume the enemy, damaging them for 2 turns",
    },
  ],
  wind: [
    {
      name: "Tornado",
      hitChance: 75,
      range: 1,
      uses: 1,
      type: "Damage",
      effect:
        "A raging vortex picks up an enemy and throws them down anywhere whithin 1-3 spaces if hit",
    },
    {
      name: "Gust",
      hitChance: 75,
      magick: -1,
      range: 1,
      uses: 1,
      type: "Radial",
      effect: "A gust of wind pushes 3 units back (horizontal pattern) if hit",
    },
    {
      name: "Static",
      hitChance: 80,
      range: 2, //1-2
      uses: 1,
      type: "Shocking",
      effect:
        "Cold and warm winds combine to electrocute the enemy, shocking them for 2 turns",
    },
  ],
  light: [
    {
      name: "Aura",
      hitChance: 85,
      magick: -1,
      resistance: 6,
      range: 1,
      uses: 1,
      type: "Damaging",
      effect: "A powerful aura covers the mage as they strike",
    },
    {
      name: "Ostracism",
      hitChance: 85,
      magick: -2,
      range: 2,
      uses: 1,
      type: "Radial",
      effect:
        "2 nonbelievers are banished (y pattern) and pushed back 2 spaces if hit",
    },
    {
      name: "Pillar Of Light",
      hitChance: 80,
      magick: 1,
      range: 2, //1-2
      uses: 1,
      type: "Burning",
      effect: "A light is summoned, so bright it burns the enemy for 2 turns",
    },
  ],
  dark: [
    {
      name: "Fluux",
      hitChance: 70,
      magick: 7,
      speed: -1,
      range: 1,
      uses: 1,
      type: "Damage",
      effect: "Woe itself strangles the enemy",
    },
    {
      name: "Tentatio",
      hitChance: 70,
      range: 1,
      uses: 1,
      type: "Radial",
      effect:
        "Three enemies (horizontal pattern) are drawn in, almost willingly",
    },
    {
      name: "Lingua",
      hitChance: 75,
      range: 2, //1-2
      uses: 1,
      type: "Poisoning",
      effect:
        "The enemy is poisoned from the inside out by words alone, damaging them for 2 turn",
    },
  ],
  gray: [
    {
      name: "Gamble of the Gods",
      hitChance: 60,
      luck: 11,
      range: 1,
      uses: 1,
      type: "Damage",
      effect: "The gods of luck roll the dice",
    },
    {
      name: "Fortuna's Choice",
      hitChance: 75,
      magick: -2,
      range: 4,
      uses: 1,
      type: "Radial",
      effect: "Any 3 units up to 4 spaces away are all eligible for misfortune",
    },
    {
      name: "Plight of the Pagan",
      hitChance: 80,
      magick: -1,
      range: 2,
      uses: 1,
      type: "Poisoning",
      effect: "A curse to the monotheistic, damaging them for 2 turns",
    },
  ],
  default: [],
};
